// @version 1.0.0
// generate-themes-manifest.ts
//
// Scans docs/html-themes/themes/ (excluding _shared) and docs/html-themes/styles/
// and emits docs/html-themes/preview/themes-manifest.js — a file://-safe global
// that preview.html loads via <script> so that dropdown population does not need
// fetch() (which is blocked on the file:// protocol).
//
// Why a manifest instead of fetch()?
//   A browser opened via file:// cannot scan the filesystem, and fetch() of local
//   JSON is blocked by the file protocol. So we generate a static .js that assigns
//   window.__THEMES_MANIFEST__ and load it with a <script> tag.
//
// Regenerate this file whenever you add or remove a theme or style:
//   bun scripts/co-deck/generate-themes-manifest.ts
//
// Usage:
//   bun scripts/co-deck/generate-themes-manifest.ts [--root <path>]
//   --root  workspace root (default: two levels above this script)

import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve, dirname } from 'path';

const args = process.argv.slice(2);
const get = (flag: string) => {
  const i = args.indexOf(flag);
  return i >= 0 ? args[i + 1] : undefined;
};

const rootArg = get('--root');
const workspaceRoot = rootArg ? resolve(rootArg) : resolve(dirname(import.meta.path), '../..');
const themesRoot = join(workspaceRoot, 'docs/html-themes/themes');
const stylesRoot = join(workspaceRoot, 'docs/html-themes/styles');
const previewDir = join(workspaceRoot, 'docs/html-themes/preview');
const manifestPath = join(previewDir, 'themes-manifest.js');

// Normalize a *_styles entry that may be a string or {name, reason?}.
function styleNameOf(entry: any): string | null {
  if (typeof entry === 'string') return entry;
  if (entry && typeof entry === 'object' && typeof entry.name === 'string') return entry.name;
  return null;
}

function listThemeDirs(): string[] {
  if (!existsSync(themesRoot)) return [];
  return readdirSync(themesRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== '_shared')
    .map((d) => d.name)
    .sort();
}

function listStyleDirs(): string[] {
  if (!existsSync(stylesRoot)) return [];
  return readdirSync(stylesRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

const themeDirs = listThemeDirs();
const styleDirs = listStyleDirs();

const themes = themeDirs.map((theme) => {
  const themeJsonPath = join(themesRoot, theme, 'theme.json');
  let compatible: string[] = [];
  let partial: string[] = [];
  if (existsSync(themeJsonPath)) {
    try {
      const tj = JSON.parse(readFileSync(themeJsonPath, 'utf-8'));
      compatible = (Array.isArray(tj.compatible_styles) ? tj.compatible_styles : [])
        .map(styleNameOf)
        .filter((s): s is string => s !== null);
      partial = (Array.isArray(tj.partial_styles) ? tj.partial_styles : [])
        .map(styleNameOf)
        .filter((s): s is string => s !== null);
    } catch {
      // Leave empty; validate-theme-styles.ts will report the JSON error.
    }
  }
  // Per-theme "styles" list = compatible_styles (the full-support set).
  // partial_styles are surfaced separately so the UI can mark them.
  return { name: theme, styles: compatible, partial_styles: partial };
});

const manifest = {
  generated_at: new Date().toISOString(),
  themes,
  styles: styleDirs,
};

if (!existsSync(previewDir)) mkdirSync(previewDir, { recursive: true });

// Emit as a script that assigns window.__THEMES_MANIFEST__.
// JSON.stringify with 2-space indent; wrap so the file is valid JS loaded via <script>.
const js =
  '// AUTO-GENERATED by scripts/co-deck/generate-themes-manifest.ts — do not edit by hand.\n' +
  '// Regenerate after adding/removing a theme or style: bun scripts/co-deck/generate-themes-manifest.ts\n' +
  'window.__THEMES_MANIFEST__ = ' + JSON.stringify(manifest, null, 2) + ';\n';

writeFileSync(manifestPath, js, 'utf-8');
console.log(`themes-manifest.js written: ${manifestPath}`);
console.log(`  themes: ${themes.map((t) => t.name).join(', ') || '(none)'}`);
console.log(`  styles: ${styleDirs.join(', ') || '(none)'}`);
