/**
 * Tenant lifecycle (ADR-0092 D4/D5): registry persistence, relocation target, and per-tenant
 * HERMES_HOME seeding. Secrets live only inside the tenant home; the generated config.yaml
 * carries the ADR-0088 D7 trust posture scoped to the tenant project directory.
 */

import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { genId, readJson, writeJson } from "./util";

export type TenantStatus = "provisioning" | "ready" | "failed";

export interface TenantRecord {
  tenantId: string;
  /** Lookup key for lazy OpenAI-surface tenants: `<variant>::<user>`; unset for native tenants. */
  key?: string;
  variant: string;
  status: TenantStatus;
  createdAt: string;
  projectDir: string;
  hermesHome: string;
  description?: string;
  error?: string;
  /** Completed Hermes turns; > 0 means the thread already exists. */
  sessions: number;
  /** Cumulative token counters from terminal result envelopes (Phase 2 quota input). */
  inputTokens: number;
  outputTokens: number;
  /** Per-UTC-day buckets for windowed quotas (`TEAM_GATEWAY_QUOTA_WINDOW=daily`); pruned to
   * the 8 most recent days on write. */
  daily?: Record<string, { turns: number; inputTokens: number; outputTokens: number }>;
  /** Antigravity-runtime conversation id (explicit continuity across turns). */
  conversationId?: string;
}

export function recordTurnUsage(
  rec: TenantRecord,
  dayKey: string,
  tokens: { input: number; output: number },
): void {
  rec.sessions += 1;
  rec.inputTokens += tokens.input;
  rec.outputTokens += tokens.output;
  const daily = (rec.daily ??= {});
  const bucket = (daily[dayKey] ??= { turns: 0, inputTokens: 0, outputTokens: 0 });
  bucket.turns += 1;
  bucket.inputTokens += tokens.input;
  bucket.outputTokens += tokens.output;
  // Prune: keep the 8 most recent day keys so the registry cannot grow unbounded.
  const keys = Object.keys(daily).sort();
  for (const key of keys.slice(0, Math.max(0, keys.length - 8))) delete daily[key];
}

/** Credential files copied from the operator's seed home. The operator's config.yaml is NEVER
 * copied — the tenant gets a generated one (trust keys only; provider config travels via env). */
const SEED_COPY_FILES = ["auth.json", ".env"];

export function tenantPaths(dataDir: string) {
  const tenantsDir = join(dataDir, "tenants");
  return { tenantsDir, registryPath: join(tenantsDir, "registry.json") };
}

export class TenantRegistry {
  private readonly records = new Map<string, TenantRecord>();
  readonly registryPath: string;

  constructor(dataDir: string) {
    const { registryPath } = tenantPaths(dataDir);
    this.registryPath = registryPath;
    for (const rec of readJson<TenantRecord[]>(registryPath) ?? []) {
      this.records.set(rec.tenantId, rec);
    }
  }

  list(): TenantRecord[] {
    return [...this.records.values()].sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  }

  get(tenantId: string): TenantRecord | undefined {
    return this.records.get(tenantId);
  }

  findByKey(key: string): TenantRecord | undefined {
    return this.list().find((rec) => rec.key === key);
  }

  upsert(rec: TenantRecord): void {
    this.records.set(rec.tenantId, rec);
    writeJson(this.registryPath, this.list());
  }

  create(init: { dataDir: string; variant: string; key?: string; description?: string }): TenantRecord {
    const tenantId = genId("gw");
    const rec: TenantRecord = {
      tenantId,
      key: init.key,
      variant: init.variant,
      status: "provisioning",
      createdAt: new Date().toISOString(),
      projectDir: join(init.dataDir, "tenants", tenantId, "project"),
      hermesHome: join(init.dataDir, "tenants", tenantId, "hermes-home"),
      description: init.description,
      sessions: 0,
      inputTokens: 0,
      outputTokens: 0,
    };
    this.upsert(rec);
    return rec;
  }
}

export function tenantConfigYaml(projectDir: string, model?: string): string {
  const lines = [
    "# Generated by team-gateway (ADR-0092 D6). Trust keys follow ADR-0088 D7:",
    "# project skills load only for the tenant project directory — never blanket.",
    "skills:",
    "  project_discovery: true",
    "  trusted_project_dirs:",
    `    - ${projectDir}`,
  ];
  if (model) {
    lines.push("", "# Model routing stamped by the gateway (TEAM_GATEWAY_HERMES_MODEL).", "model:", `  default: "${model}"`);
  }
  return lines.join("\n") + "\n";
}

export function seedHermesHome(rec: TenantRecord, seedHome?: string, model?: string): void {
  mkdirSync(rec.hermesHome, { recursive: true });
  if (seedHome && existsSync(seedHome)) {
    for (const name of SEED_COPY_FILES) {
      const src = join(seedHome, name);
      if (existsSync(src)) copyFileSync(src, join(rec.hermesHome, name));
    }
  }
  writeFileSync(join(rec.hermesHome, "config.yaml"), tenantConfigYaml(rec.projectDir, model));
}

/** Public shape for API responses — internal paths stay server-side. */
export function publicTenant(rec: TenantRecord) {
  return {
    tenantId: rec.tenantId,
    key: rec.key,
    variant: rec.variant,
    status: rec.status,
    createdAt: rec.createdAt,
    description: rec.description,
    sessions: rec.sessions,
    usage: { inputTokens: rec.inputTokens, outputTokens: rec.outputTokens },
    error: rec.error,
  };
}
