/**
 * Subprocess tests for verify-skills.ts curated-index protection and --check
 * drift gate (U-20261006-002).
 *
 * verify-skills.ts resolves its project root from its own file location, so
 * each case stages a disposable fixture project under the OS temp dir, copies
 * the script into <fixture>/scripts/, and runs it as a subprocess.
 *
 * Contract under test:
 *  - A SKILLS.md whose FIRST line is exactly "# Skills Index" is a generated
 *    stub — regenerable in both modes.
 *  - A SKILLS.md whose first line merely STARTS WITH that prefix (e.g.
 *    "# Skills Index - test") is curated — never rewritten in any mode.
 *  - `--check` on a stale curated file exits 1 (path + first differing line),
 *    writes nothing; on a missing/exact-stub file it regenerates and exits 0.
 *
 * @version 1.0.0
 */
import { describe, test, expect, afterAll } from 'bun:test';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const REPO_ROOT = join(import.meta.dir, '..', '..');
const SCRIPT_SRC = join(REPO_ROOT, 'scripts', 'verify-skills.ts');
const TEMP_ROOTS: string[] = [];

afterAll(() => {
  for (const root of TEMP_ROOTS) rmSync(root, { recursive: true, force: true });
});

const VALID_SKILL = [
  '---',
  'name: demo-skill',
  'description: Demo skill for the verify-skills fixture.',
  'metadata:',
  '  type: testing',
  '---',
  '',
  'This body is intentionally longer than fifty characters so the',
  'content-length warning never fires in this fixture.',
  '',
].join('\n');

const CURATED = [
  '# Skills Index - test',
  '',
  'Curated index for the fixture project. verify-skills.ts must never',
  'rewrite this file in any mode.',
  '',
].join('\n');

const STALE_STUB = [
  '# Skills Index',
  '',
  '> Auto-generated by verify-skills.ts. Do not edit manually.',
  '',
  'Generated: 2020-01-01T00:00:00.000Z',
  '',
].join('\n');

function stageFixture(skillsMd: string | null): string {
  const root = mkdtempSync(join(tmpdir(), 'verify-skills-fixture-'));
  TEMP_ROOTS.push(root);
  mkdirSync(join(root, 'scripts'), { recursive: true });
  mkdirSync(join(root, 'skills', 'demo-skill'), { recursive: true });
  copyFileSync(SCRIPT_SRC, join(root, 'scripts', 'verify-skills.ts'));
  writeFileSync(join(root, 'skills', 'demo-skill', 'SKILL.md'), VALID_SKILL);
  if (skillsMd !== null) writeFileSync(join(root, 'skills', 'SKILLS.md'), skillsMd);
  return root;
}

function runVerifySkills(root: string, extraArgs: string[] = []): { exitCode: number; stdout: string; stderr: string } {
  const proc = Bun.spawnSync(['bun', join(root, 'scripts', 'verify-skills.ts'), ...extraArgs], {
    cwd: root,
    stdout: 'pipe',
    stderr: 'pipe',
  });
  return {
    exitCode: proc.exitCode ?? -1,
    stdout: new TextDecoder().decode(proc.stdout),
    stderr: new TextDecoder().decode(proc.stderr),
  };
}

const skillsMd = (root: string) => join(root, 'skills', 'SKILLS.md');

describe('verify-skills curated-index protection (U-20261006-002)', () => {
  test('non-check mode never rewrites a curated first line (prefix, not exact)', () => {
    const root = stageFixture(CURATED);
    const res = runVerifySkills(root);
    expect(res.exitCode).toBe(0);
    expect(readFileSync(skillsMd(root), 'utf-8')).toBe(CURATED);
  });

  test('--check on a stale curated file exits 1, reports the path, writes nothing', () => {
    const root = stageFixture(CURATED);
    const res = runVerifySkills(root, ['--check']);
    expect(res.exitCode).toBe(1);
    expect(res.stderr).toContain('SKILLS.md drift');
    expect(res.stderr).toContain(skillsMd(root));
    expect(res.stderr).toContain('first differing line: 1');
    expect(readFileSync(skillsMd(root), 'utf-8')).toBe(CURATED);
  });

  test('--check regenerates an exact generated stub and exits 0', () => {
    const root = stageFixture(STALE_STUB);
    const res = runVerifySkills(root, ['--check']);
    expect(res.exitCode).toBe(0);
    const after = readFileSync(skillsMd(root), 'utf-8');
    expect(after.split('\n', 1)[0]).toBe('# Skills Index');
    expect(after).not.toBe(STALE_STUB); // regenerated with a fresh Generated: line
    expect(after).toContain('- [demo-skill](skills/demo-skill/SKILL.md)');
  });

  test('--check with a missing SKILLS.md regenerates it and exits 0 (not drift)', () => {
    const root = stageFixture(null);
    const res = runVerifySkills(root, ['--check']);
    expect(res.exitCode).toBe(0);
    expect(readFileSync(skillsMd(root), 'utf-8')).toContain('# Skills Index');
  });

  test('non-check mode keeps the legacy UX: a missing index is auto-generated, exit 0', () => {
    const root = stageFixture(null);
    const res = runVerifySkills(root);
    expect(res.exitCode).toBe(0);
    expect(readFileSync(skillsMd(root), 'utf-8')).toContain('# Skills Index');
  });
});
