/**
 * Legacy skills-index disposition tests (U-20261006-002)
 * @version 1.0.0
 *
 * verify-skills.ts must never mutate the registry it verifies by default:
 * - only a file whose first line is exactly "# Skills Index" is generated-format
 *   legacy stub (curated variant indexes and lifecycle registries are NOT);
 * - the render is deterministic (no wall-clock timestamp);
 * - default run reports drift without writing; --check-index exits 1 on drift;
 *   --write-index regenerates explicitly.
 */

import { describe, expect, test, afterAll } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  isExactLegacyIndex,
  legacyIndexDisposition,
  parseIndexFlags,
  renderSkillsIndex,
  type SkillCheck,
} from "../../scripts/verify-skills.ts";

const LEGACY_STUB = "# Skills Index\n\n> Auto-generated by verify-skills.ts.\n\n- [a](skills/a/SKILL.md)\n";
const CURATED_VARIANT = "# Skills Index - co-security\n\ncurated 6-skill security index\n";
const LIFECYCLE_REGISTRY = "# SKILLS.md — Skill Lifecycle Registry\n\n| skill | version |...\n";

function check(name: string, path: string): SkillCheck {
  return { name, path, status: "PASS", issues: [] };
}

describe("isExactLegacyIndex (U-20261006-002)", () => {
  test('exact "# Skills Index" first line is legacy', () => {
    expect(isExactLegacyIndex(LEGACY_STUB)).toBe(true);
    expect(isExactLegacyIndex("# Skills Index\r\n\r\nbody\r\n")).toBe(true);
  });

  test("curated variant index is NOT legacy (co-security overwrite class)", () => {
    expect(isExactLegacyIndex(CURATED_VARIANT)).toBe(false);
  });

  test("lifecycle registry is NOT legacy", () => {
    expect(isExactLegacyIndex(LIFECYCLE_REGISTRY)).toBe(false);
  });
});

describe("renderSkillsIndex determinism", () => {
  const tmp = mkdtempSync(join(tmpdir(), "verify-skills-idx-"));
  afterAll(() => rmSync(tmp, { recursive: true, force: true }));

  test("two renders of the same checks are byte-identical (no timestamp)", () => {
    const checks = [check("a", "/nonexistent/a/SKILL.md"), check("b", "/nonexistent/b/SKILL.md")];
    expect(renderSkillsIndex(checks)).toBe(renderSkillsIndex(checks));
  });

  test("render starts with the legacy header and lists readable skills", () => {
    const skillDir = join(tmp, "alpha");
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(join(skillDir, "SKILL.md"), "---\nname: alpha\ndescription: probe\n---\n\nBody.\n");
    const out = renderSkillsIndex([check("alpha", join(skillDir, "SKILL.md"))]);
    expect(out.startsWith("# Skills Index\n")).toBe(true);
    expect(out).toContain("- [alpha](skills/alpha/SKILL.md)");
  });
});

describe("legacyIndexDisposition (U-20261006-002)", () => {
  const generated = renderSkillsIndex([]);

  test("default: drift reported, NO write, exit 0", () => {
    const d = legacyIndexDisposition("# Skills Index\n\nstale content\n", generated, {});
    expect(d.write).toBe(false);
    expect(d.exitCode).toBe(0);
    expect(d.note).toContain("NOT rewritten implicitly");
  });

  test("default: absent file reported, NO write, exit 0", () => {
    const d = legacyIndexDisposition(null, generated, {});
    expect(d.write).toBe(false);
    expect(d.exitCode).toBe(0);
    expect(d.note).toContain("absent");
  });

  test("--check-index: drift exits 1 without writing", () => {
    const d = legacyIndexDisposition("# Skills Index\nstale\n", generated, { checkIndex: true });
    expect(d.write).toBe(false);
    expect(d.exitCode).toBe(1);
  });

  test("--check-index: match exits 0 with no note", () => {
    const d = legacyIndexDisposition(generated, generated, { checkIndex: true });
    expect(d.exitCode).toBe(0);
    expect(d.note).toBeNull();
  });

  test("--write-index: regenerates explicitly (drift or absent), exit 0", () => {
    expect(legacyIndexDisposition("# Skills Index\nstale\n", generated, { writeIndex: true }).write).toBe(true);
    expect(legacyIndexDisposition(null, generated, { writeIndex: true }).write).toBe(true);
    expect(legacyIndexDisposition(generated, generated, { writeIndex: true }).exitCode).toBe(0);
  });

  test("CRLF on disk does not count as drift against LF render", () => {
    const d = legacyIndexDisposition(generated.replace(/\n/g, "\r\n"), generated, { checkIndex: true });
    expect(d.exitCode).toBe(0);
  });
});

describe("parseIndexFlags", () => {
  test("recognizes the three flags and ignores positionals", () => {
    const f = parseIndexFlags(["--check-index", "some.json"]);
    expect(f.checkIndex).toBe(true);
    expect(f.writeIndex).toBe(false);
    expect(parseIndexFlags(["--write-index"]).writeIndex).toBe(true);
    expect(parseIndexFlags(["-h"]).help).toBe(true);
    expect(parseIndexFlags([]).checkIndex).toBe(false);
  });
});
